### ISSUE TITLE
[Umbrella] Support gaps

### ISSUE THREAD

**Issue by Airblader** [i3/i3#3724]
## Known issues / possible improvements

- [x] Ensure gaps work with titlebars without a compositor: https://github.com/i3/i3/issues/1966
- [x] Window size isn’t evenly distributed, in particular with large gaps: https://github.com/i3/i3/pull/5252
- [ ] #5253

---

Original issue text:

## Desired Behavior

After a recent discussion between @stapelberg and myself, we would like to reconsider bringing gaps into i3 itself, effectively deprecating i3-gaps. The main rationale here is that there clearly are thousands of users who want gaps.

In order to do so, we need to implement not only gaps, but also all of the current i3-gaps features as listed below. This issue serves as an umbrella issue, if necessary we can create separate issues for the individual features. Before work on this can be started, we need to state our expectations:

1. This is **not** about simply porting the gaps patch into i3. The current gaps patch is kept simple enough to make upstream maintenance possible; this means, however, that in many ways it is more of a hack and doesn't live up to our quality expectations. We should therefore consider – and discuss – how gaps can be brought into i3 in a clean way, particularly including support for titlebars.
2. At this point in time, there is no final decision on whether we would merge this. It very much depends on the discussion and the solution we can find.

# Gaps
This list tracks the core gaps features that need to be supported

- [x] Current i3-gaps configuration and command surface:
    - Configuration: `gaps [inner|outer|horizontal|vertical|top|left|bottom|right] <px>`
    - Configuration: `workspace <ws> gaps [inner|outer|horizontal|vertical|top|left|bottom|right] <px>`
    - Command: `gaps inner|outer|horizontal|vertical|top|right|bottom|left current|all set|plus|minus|toggle <px>`
- [x] Make gaps information properly available on the IPC (required for in-place restart)
- [x] Provide tests for gaps

We should overall strive to be compatible with i3-gaps to minimize friction, but where sensible we may deviate. For example, workspace-level gaps are currently solved a bit awkward in i3-gaps.

# Gaps-related features
The following list tracks other features that need to be supported in i3 as well¹.

- [x] `smart_gaps on | inverse_outer`
- [x] `smart_borders no_gaps`²
- [x] `hide_edge_borders smart_no_gaps`

¹ Note that we may choose to rename features if necessary.
² `smart_borders on` is an alias for `hide_edge_borders smart` and will thus be ignored here.

Linking related issues for visibility: #1474, #3611, #2890 

Please keep the discussion on this issue solely about how to move gaps to i3. Other questions or feature requests should be posted as new issues. As this will likely be a long and technical discussion I will hide any off topic comments. Thank you! 

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.16.1
</pre>

**Comment by Airblader** [comment]
In order to implement gaps properly in i3, I believe #1966 might be a required upfront change. I think ideally a gaps implementation would inset the entire rect of a container rather than just the window_rect (open for discussion, of course). Ideally gaps would not require a compositor.

Interesting things to consider are things like snapping the cursor for resizing and the resize indicator line.

**Comment by rndusr** [comment]
I've always wanted an option that allows me to limit the space a single window can occupy. For example, if I open terminal on an empty workspace, the prompt is at the very top-left corner, which can be awkward to focus on a large monitor. And it will always stay at the left edge, which is also not in the center of my vision. I usually work around this by opening another terminal so that the prompt is at the center, but is that the best solution?

I'm not sure if I understand the `smart_gaps` option correctly. Would that allow me to limit the size of single windows? If not, would it be something worth implementing?

**Comment by Natureshadow** [comment]
Please bear with me while not posting something technically relevant, but I want to express that I am very much in support of getting this into vanilla i3, also from a distribution point of view. I am very happy that a new contributor in Debian who wanted i3-gaps led to i3-gaps probably being refused into Debian, but new efforts to remove the requirement for it have arisen from it, which will with a bit of luck make life easier for all distributions and users ☺!

Thank you, both upstreams!

**Comment by Airblader** [comment]
I appreciate both your comments, it I would please ask to stay on topic here. This is likely goimg to be a long and technical discussion, so I would like to avoid +1 noise, questions about how i3-gaps currently works or additional feature requests. This issue is about supporting what i3-gaps can do in i3.

**Comment by stapelberg** [comment]
> Ideally gaps would not require a compositor.

I’d like to make this requirement a bit stronger: gaps between windows must be possible with or without a compositor. For advanced features like transparency, a compositor may be required (I don’t know).

**Comment by skontar** [comment]
Hi. This is a great news. 

My most favourite feature from gaps is https://github.com/Airblader/i3/#bar-height which allows me to have reasonably big tray icons and workspace buttons with a smaller text and bit of padding everywhere.

I use something like: 
```
    font pango: FontAwesome, Hack 11.5
    height 32
```

Could you please consider supporting this feature also?

Thanks!

**Comment by Airblader** [comment]
@skontar The non-gaps related issues have separate issues, see #3721

**Comment by budRich** [comment]
A community is directed by the most intolerant minority. With i3 that used to be @Airblader (on reddit), and @stapelberg (github), that was good (since both of them are good and intelligent people). Now it is  ubuntu users who don't know which version they have installed who rule it all. 

I will not "upvote" this issue, but i don't dismiss it either.

It is probably a good idea to add gaps to i3. I guess this will mean that i3-gaps will get archived causing less confusion, better package manager support, and most importantly a more focused project workflow for @Airblader .

---

i3-less  
 - no gaps
 - no internal managing of keybindings
 - no internal bar

**Comment by xPMo** [comment]
Given the work the Sway folks have put in implementing gaps (and other i3-gaps features) "correctly" from the start, is the sway project a good place to refer for implementation? Or is compositing too integrated in that project for i3?

**Comment by Airblader** [comment]
I have no idea how sway or Wayland work but my feeling is that it wouldn't be very useful.

**Comment by Al-Caveman** [comment]
In my view, title bars should be re-implemented anyway for many reasons.  Yet another reason is:  better compatibility with other apps, such as GIMP.  E.g. taking a screenshot of a window, with windows decoration (in GIMP), does not work, simply because the title bar is a separate window.  So the current implementation of _title-bars-as-windows_ is semantically false, and is causing issues with others apps.

I think this would be also a nice opportunity to do things more correctly.  Specifically, I think the concepts of _stacking_ and _tabbing_ should be merged.  Technically, _stacking_ is just an inefficient _tab_ that needlessly wastes more horizontal space.  _Tabbing_ is not perfect either, as it needlessly squeezes too many tabs, up to a point when the text in the title is too unreadable.

I suggest, while re-doing title bars, to introduce _smart tabs_, which work as follows:

1. Tabs  initially work as normal tabs in `i3`.
2. When number of tabs increase beyond certain limits, or if title's text gets squeezes up to certain limit, then simply add another tabs row.  _Alternatively_, one could manually create a new tabs row.

Additionally, I suggest this usability enhancement:  make tabbed windows as a single browsing unit, so when we use `mod+left/right/top/down`, we don't end up shuffling tabs, and we don't end up hitting a moment _"Oh I should've selected all, by `mod+a+a...+a` first!"_.   Instead, we use other key combinations specific for tab shuffling.  This is more usable than needing to hit `mod+a` every time one wants to move across a tabbed tile without wanting to also shuffle the tab.  IMO it is better to isolate (1) tile movement from (2) tab shuffling.

As for backwards compatibility, old tabs/stacks could be simply mapped into _smart tags_.  It will be backwards compatible in every sense, except that it will have the side effect of having greater utility per pixel.  If a tabbing/stacking-user wants to have maximum backwards compatibility with stacks, he can map the tab-shuffling keys to `mod+up` and `mod+down` keys.  But I suspect that most people will not do so.

Tabbing/stacking are, fundamentally, great features as they map to the concept _"minimize"_ in floating windows (except not needing to fall in the inefficient tasks bar, but rather distribute across the monitor).  It's sad that they are not very usable in the current implementation, and hence my suggestions above.

**Comment by stapelberg** [comment]
> I think this would be also a nice opportunity to do things more correctly. Specifically, I think the concepts of _stacking_ and _tabbing_ should be merged. Technically, _stacking_ is just an inefficient _tab_ that needlessly wastes more horizontal space. _Tabbing_ is not perfect either, as it needlessly squeezes too many tabs, up to a point when the text in the title is too unreadable.
> 
> I suggest, while re-doing title bars, to introduce _smart tabs_, which work as follows:
> 
> 1. Tabs  initially work as normal tabs in `i3`.
> 2. When number of tabs increase beyond certain limits, or if title's text gets squeezes up to certain limit, then simply add another tabs row.  _Alternatively_, one could manually create a new tabs row.

We had this in i3 v3.x and dropped it with the v4.x series. It was a niche feature whose little use didn’t justify the complexity.

As for the rest of your comment, can you post your _individual_ suggestions as separate feature requests please? A grab-bag of thoughts in an unrelated issue is not the best way to have a discussion :)

Thank you.

**Comment by Airblader** [comment]
What @stapelberg said, but with the addition that the first part of your comment (thanks for that!) seems to be #1966, I think.

**Comment by gonzolively** [comment]
🦗🦗🦗

**Comment by ghost** [comment]
It's been a while since there has been activity on this issue. Just wondering if any progress is being made and if any help is required (e.g., testing).

**Comment by orestisfl** [comment]
@sierratango88 none that I am aware of

**Comment by davralin** [comment]
[This](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909646) is a relevant RFP from Debian, and someone stepped up for the packaging [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=930557) - but was rejected because this was supposed to be merged instead.

That looks to be the last movement with regards to this.

For the Record, I made the RFP.

**Comment by staxfur** [comment]
Hey, may I ask what the current situation about this is? The gaps feature is already implemented thanks to @Airblader, so what's needed to finish the merge? Would be really nice to have unified version. I'd also look into contributing to this when additional work is needed.

Thank you really much!

**Comment by Airblader** [comment]
There is no current status besides what you see here. That is to say that no one is working on or has worked on this.

Please read the points in the starting comment of this thread for an explanation why this isn't about "merging i3-gaps", but about a fairly significant amount of work.

**Comment by electron271** [comment]
I would be willing to take the pain of attempting to support gaps. It would be annoying, but what's life without a little pain?

**Comment by electron271** [comment]
I will start with using some of the i3-gaps code, then fixing any bugs, and hopefully make them work together!

**Comment by budRich** [comment]
>I will start with using some of the i3-gaps code, then fixing any bugs, and hopefully make them work together!

^ that goes against everything OP was asking for.

> 1. This is not about simply porting the gaps patch into i3.
----
from i3wm.org:  

> 8. Don’t be bloated, don’t be fancy (simple borders are the **most** decoration we want to have).

---
gaps are bloated, complicated borders that don't jam with i3wm advanced layout capabilities.

**Comment by budRich** [comment]
edit:
wait was my previous post un-off-topiced? in that case, disregard the previous text of this very post.

**Comment by stapelberg** [comment]
I have marked the previous comments as outdated, because despite what i3wm.org says and how you might interpret that, we (the i3 maintainers) have agreed to consider merging i3-gaps in earnest. This is not up for discussion, so rest assured that any serious work on gaps will be reviewed by us.

**Comment by Airblader** [comment]
We recently discussed possibly accelerating this process further by lifting the restriction to solve all problems upfront. This would instead mean merging i3-gaps more "as-is" into i3, accepting the limitations, and leaving it to future work to resolve them.

The i3-gaps repository would probably be put into archive mode (once a released i3 version with gaps exists) and refer to i3 instead, giving package maintainers some time to transition.

However, a few points need to be addressed even in this accelerated scenario IMO:

* [x] Add documentation to the user guide for gaps.
    * [x] Add documentation on the limitations. Possibly we even just mark gaps as some experimental feature.
* [x] Decide what this means for #3721.
* [x] Add at least some basic tests for gaps and gaps-related features. This might be a soft requirement.
* [x] Change the `gaps` command to operate on windows/containers instead of workspaces?
    * decided against it: want to retain maximum compatibility for people who switch from i3-gaps to i3

WDYT @stapelberg, anything else we'd consider required for this?

**Comment by stapelberg** [comment]
Thanks for summarizing what we talked about :) Good timing, too, as I was planning to spend some time on looking into gaps today. 

Your list of points looks reasonable to me.

I have started the process of merging what’s currently in your tree, and will address the list one by one before sending a PR to review. The current status can be seen here: https://github.com/stapelberg/i3/commits/gaps

**Comment by stapelberg** [comment]
I updated your list to also mention the `gaps` command currently operating on workspaces. I think it would be more useful if the command operated on windows/containers. It can still be used on the workspace level, but could also be used on a window level.

That said, I’m not sure how many people use the `gaps` command at runtime at all — personally, I would just use the `gaps` config directive once. Do people need specific gap sizes for specific types of windows? If so, in which situations (examples please)?

---

I have also updated my branch to contain an initial userguide change. If you know of more limitations compared to what I’m describing there, please let me know :)

**Comment by Airblader** [comment]
> That said, I’m not sure how many people use the gaps command at runtime at all

I believe it isn't as uncommon as you might assume. Even just toggling gaps on/off is something people want to do.

> Do people need specific gap sizes for specific types of windows? If so, in which situations (examples please)?

The request did come up a few times over the years, but it was never a commonly asked for feature. 

Edit: see https://github.com/Airblader/i3/issues/379

Given the new goal I think it'd be better to consider any semantical changes in separate issues. Syntax-wise we can't make any changes anyway since the goal is to make the switch from i3-gaps to i3 smooth and not require changes, right?

**Comment by Airblader** [comment]
I left some comments on the commits themselves.

> If you know of more limitations compared to what I’m describing there, please let me know :)

When you open a few windows, the size is not evenly distributed. This isn't noticable with "normal" gap sizes, but quite noticable if you have big gaps. See https://github.com/Airblader/i3/issues/22 / https://github.com/Airblader/i3/issues/396. Perhaps we just migrate the issue, not sure we need to document it in the user guide.

@cameronleger posted a patch for this (that I somehow missed for years) in the first issue. Haven't looked at it, though, but perhaps we can upstream it.

**Comment by stapelberg** [comment]
Thanks for the extra infos. Yeah, let’s keep the behavior as-is for the `gaps` command then.

I added the part about un-evenly distributed sizes to the list in the first comment of this issue.

**Comment by stapelberg** [comment]
Gaps has landed in the i3 “next” branch! Feel free to give it a shot.

The documentation is at https://build.i3wm.org/docs/userguide.html#gaps

**Comment by Airblader** [comment]
@stapelberg Whats the plan for the RGBA visuals in i3bar? That'd be needed still, right?

**Comment by stapelberg** [comment]
> @stapelberg Whats the plan for the RGBA visuals in i3bar? That'd be needed still, right?

Yeah, it’s the last remaining diff between your tree and `next`. 

What’s the easiest/best way to check if the feature works? I also vaguely remember some back-and-forth with it, so I wanted to look into the history more before sending a PR for it.

**Comment by Airblader** [comment]
> What’s the easiest/best way to check if the feature works?

Play with transparency for i3bar background and text color. Specific scenario: fully transparent text on opaque background.

> I also vaguely remember some back-and-forth with it

Yeah, i3-gaps now ended up using a different operator I believe. I had to choose this one because the alpha levels of background and text shouldn't be multiplied. Think of the above scenario: the text shouldn't just be invisible, it should stamp a hole of transparency into the bar.

**Comment by pietryszak** [comment]
> Gaps has landed in the i3 “next” branch! Feel free to give it a shot.
> 
> The documentation is at https://build.i3wm.org/docs/userguide.html#gaps
![image](https://user-images.githubusercontent.com/45850093/199605292-65c1832c-3a55-4e4e-ada3-fed7926243be.png)
Thank you :)

**Comment by Airblader** [comment]
@stapelberg It seems we forgot to add docs for

* `hide_edge_borders smart_no_gaps`
* `smart_borders`

**Comment by bfrg** [comment]
Thank you for doing this. The first few years I was using the original i3 without gaps but eventually I realized that having small gaps between windows feels more comfortable, I can't really explain why. With gaps the windows have some kind of space to "breathe" (so to speak), and it doesn't look like everything is tucked together. Nevertheless, there seems to be a bug in i3-gaps when switching layouts, see https://github.com/Airblader/i3/issues/301. It would be nice if this issue was eventually addressed.

**Comment by stapelberg** [comment]
> Nevertheless, there seems to be a bug in i3-gaps when switching layouts, see [Airblader/i3#301](https://github.com/Airblader/i3/issues/301). It would be nice if this issue was eventually addressed.

Yes, we know. This issue is prominently documented in the userguide (https://build.i3wm.org/docs/userguide.html#gaps), so we don’t need any more reports of it :) You can follow https://github.com/i3/i3/issues/1966 for more details if you’re curious. 

I’ll try and resume further work on this over the weekend.

**Comment by stapelberg** [comment]
The long-standing graphical corruption artifacts issue with i3-gaps (which required either turning off title bars or running a compositor) is now fixed! 🎉

Please give it a try by upgrading to the latest “next” branch version and let us know in case you notice something still wrong

**Comment by davralin** [comment]
Somewhat unrelated, Are there any plans to make a release with this merged soon-ish?

As far as I remember @stapelberg - you are still the package maintainer for the Debian package, and bookworm's freeze is coming up.. :)

Would be really great to see this making it into bookworm!

**Comment by stapelberg** [comment]
No, sur5r has taken over the Debian packaging work since i3 v4.17 (thank you!)

I have considered doing a release with this feature earlier than the usual cadence because of its significance. 

The earliest I can imagine is early/mid December, or possibly January depending on how many user reports we get in terms of breakage or successful test reports.

Debian’s soft freeze starts at 2023-02-12, so with a release in January (preferably early), that would leave sur5r a few weeks to upload it to Debian to make it into bookworm.

**Comment by vincentbernat** [comment]
I have switched to next. I am only using `inner gaps 10` in my configuration and I had to switch to `inner gaps 5` to get the same gaps. Otherwise, everything seems to run smoothly.

**Comment by stapelberg** [comment]
> I have switched to next. I am only using `inner gaps 10` in my configuration and I had to switch to `inner gaps 5` to get the same gaps. Otherwise, everything seems to run smoothly.

You’re probably using 2x scaling on a hi-dpi display then? We added hi-dpi support to gaps, but the consequence is the change you needed :) https://github.com/i3/i3/commit/6b658f88be50d5251f85eaf6f838d6c67ebaac95

**Comment by vincentbernat** [comment]
Yes, that's it! Thanks!

**Comment by vincentbernat** [comment]
> The long-standing graphical corruption artifacts issue with i3-gaps (which required either turning off title bars or running a compositor) is now fixed! tada
> 
> Please give it a try by upgrading to the latest “next” branch version and let us know in case you notice something still wrong

Previously, despite the compositor, I didn't get the title bar on Monkey Island running on Steam on Linux on a tabbed layout. It works now.

**Comment by stapelberg** [comment]
> > I have switched to next. I am only using `inner gaps 10` in my configuration and I had to switch to `inner gaps 5` to get the same gaps. Otherwise, everything seems to run smoothly.
> 
> You’re probably using 2x scaling on a hi-dpi display then? We added hi-dpi support to gaps, but the consequence is the change you needed :) [6b658f8](https://github.com/i3/i3/commit/6b658f88be50d5251f85eaf6f838d6c67ebaac95)

Actually, there was something wrong in this area after all: try upgrading to latest `next` (at least commit https://github.com/i3/i3/commit/69e13d782176ca5d2cade4d4327fdf84d7ceb3b4) and see if your old config works without changes.

**Comment by stapelberg** [comment]
Alright, with the PR #5252 merged, all remaining work items for gaps are done, so I’m closing this issue! 🎉

(The only remaining enhancement I’m aware of is tracked in https://github.com/i3/i3/issues/5253)

If you haven’t already, please switch to i3-git (`next` branch, commit e6a28b9 or newer)  and verify that everything works as you expect it to.

To get a new release out the door soon, we need as many people as possible to help testing, so we have a chance to fix any issues before the release :) Please file new issues for any bugs you encounter. Thanks in advance!

**Comment by pietryszak** [comment]
@Airblader When a gaps is merged to main i3, what's happen with i3-gaps?

A i3-gaps repo comes to archive status, and start a  new era of cooperation between you and @stapelberg?

**Comment by Airblader** [comment]
@pietryszak I have just now archived the i3-gaps repository.

I've been a contributor and maintainer for i3 for years now, so we've been cooperating for many years already. 😉

**Comment by vincentbernat** [comment]
> > > I have switched to next. I am only using `inner gaps 10` in my configuration and I had to switch to `inner gaps 5` to get the same gaps. Otherwise, everything seems to run smoothly.
> > 
> > 
> > You’re probably using 2x scaling on a hi-dpi display then? We added hi-dpi support to gaps, but the consequence is the change you needed :) [6b658f8](https://github.com/i3/i3/commit/6b658f88be50d5251f85eaf6f838d6c67ebaac95)
> 
> Actually, there was something wrong in this area after all: try upgrading to latest `next` (at least commit [69e13d7](https://github.com/i3/i3/commit/69e13d782176ca5d2cade4d4327fdf84d7ceb3b4)) and see if your old config works without changes.

I have updated and I had to revert the value for `inner gaps` as well.

**Comment by verfriemelt-dot-org** [comment]
> @pietryszak I have just now archived the i3-gaps repository.
> 
> I've been a contributor and maintainer for i3 for years now, so we've been cooperating for many years already. wink

thank you both @Airblader and @stapelberg !! much appreciated :)
