### ISSUE TITLE
Release 4.18.2 bugfix release

### ISSUE THREAD

**Issue by orestisfl** [i3/i3#4097]
From https://github.com/i3/i3/issues/3979#issuecomment-630962891

PRs:
* [x] commit 5eab604a105f10f2ae275f2c05989ccd19b3373a (PR #4012)
  * [ ] Release note: https://github.com/i3/i3/blob/0c0aef84fafb521ca32da9f92594343ec4579612/RELEASE-NOTES-next#L40
* [ ] commit 5e2f13a28c4fd7348914dfd999026d0e30424cd5 (PR #4041)
  * [ ] This might be tricky to cherry-pick because it applies on 4.18.1 but it comes on top of https://github.com/i3/i3/pull/4006
  * [ ] Now that I think of it, this should have had a release note as well, since it is not a regression
  * [x] I'll run the tests on 4.18.1 again and verify it crashes
* [x] commit 0fb56a92d06a2742017a64bbfa8c9393eb0e251f (PR 4084)
  * [ ] Needs release note
  * [x] Needs confirmation in https://github.com/i3/i3/issues/4048
* [x] commit 025743eaf9c993e57c7fdd20127078b835bcd2c0 (PR 4140)

**Comment by i3bot** [comment]
I don’t see a link to logs.i3wm.org. Did you follow https://i3wm.org/docs/debugging.html? (In case you actually provided a link to a logfile, please ignore me.)

**Comment by i3bot** [comment]
I don’t see a version number. Could you please copy & paste the output of `i3 --version` into this issue?

**Comment by orestisfl** [comment]
>  I'll run the tests on 4.18.1 again and verify it crashes

The crash does not happen after all because `con_is_floating` refuses to change the state:
```
05/19/2020 10:58:52 PM - handlers.c:handle_client_message:856 - The window was requested to be visible on all workspaces, making it sticky and floating.
05/19/2020 10:58:52 PM - Container is a dock window, not enabling floating mode.
05/19/2020 10:58:52 PM - ewmh.c:ewmh_update_sticky:279 - Setting _NET_WM_STATE_STICKY for window = 4194306.
```

however, the (minor) bug here is that _NET_WM_STATE_STICKY is set. So far, this doesn't lead to any known crashes because we don't use the `->sticky` state this much throughout the code.

WDYT?

**Comment by 333fred** [comment]
Is there any update on this yet? I'm still getting annoyed daily by [the notifications bug](https://github.com/i3/i3/issues/3979).

**Comment by stapelberg** [comment]
> WDYT?

So, do I understand correctly that this commit is not required to cherry-pick for the 4.18.2 release after all? I’d rather play it safe for bugfix releases and do minimal changes.

**Comment by stapelberg** [comment]
I have pushed the remaining commits: https://github.com/i3/i3/commits/stable

Once @orestisfl confirms, we can go ahead with the release.

**Comment by orestisfl** [comment]
SGTM! Remember the release notes.

**Comment by stapelberg** [comment]
Thank you. Will try to get the release out today!

**Comment by stapelberg** [comment]
Now released! https://i3wm.org/downloads/RELEASE-NOTES-4.18.2.txt
