### ISSUE TITLE
Next release (4.19)

### ISSUE THREAD

**Issue by orestisfl** [i3/i3#4220]
# Issues for i3 4.19

Easy things we should fix:
- [x] i3-dmenu-desktop order: https://github.com/i3/i3/issues/4031
- [x] parse_error docs: https://github.com/i3/i3/issues/4166
- [x] default config: no-startup-id for dmenu: https://github.com/i3/i3/issues/4216

Issues we need to investigate:
- [x] debian package build failure: https://github.com/i3/i3/issues/4136
- [x] https://github.com/i3/i3/issues/4086 (meson)

# Issues for i3 4.18.3

Important issues:
- [x] https://github.com/i3/i3/issues/4159 (regression from 4.18.2)
  - [x] Mention this in the release notes as well

**Comment by i3bot** [comment]
I don’t see a link to logs.i3wm.org. Did you follow https://i3wm.org/docs/debugging.html? (In case you actually provided a link to a logfile, please ignore me.)

**Comment by i3bot** [comment]
I don’t see a version number. Could you please copy & paste the output of `i3 --version` into this issue?

**Comment by Airblader** [comment]
FWIW I think timing-wise a 4.19 would make sense.

**Comment by stapelberg** [comment]
Let’s do a minor bugfix release first, then do a 4.19 in a few weeks with the meson changes.

That way, meson won’t be in the critical path for people who are suffering from the current bugs :)

**Comment by stapelberg** [comment]
So, just to be extra double triple clear: I have cherry-picked commit 838b600fead202416013db5c1b57f7031f06bed6 into [the stable branch](https://github.com/i3/i3/commits/stable) as the only change on top of our last stable release 4.18.2.

This is all we need to make a useful 4.18.3 release, yes? @orestisfl

**Comment by orestisfl** [comment]
@stapelberg Yes!

**Comment by stapelberg** [comment]
Great, thanks for confirming. I’ll try to get this out later today.

**Comment by stapelberg** [comment]
4.18.3 now released. Re-titling this for 4.19, but that’ll happen over the next few weeks I think

**Comment by eleksir** [comment]
May i insert my 2 cents to this discussion?
#4170 
This issue make non-meson builds to fail. Either definely switch to meson (and get rid of autotools stuff) or fix this issue to consider 4.18.x stable.

**Comment by orestisfl** [comment]
We plan to get rid of the autotools stuff in 4.19

**Comment by eleksir** [comment]
Nice to read this. I'm very hope that it would be trouble-free transition. "Perl way" in this case confuses maintainers of i3wm package. And autotools is kind of "pain in the butt" for programmers. 
But autotools is still persists in 4.18 series of i3, so it would be nice to review mentioned defect. Well, at least i hope that you still care not only about users but about those who maintain binary packages of i3 too.

**Comment by stapelberg** [comment]
Went through the open issues and added a few to https://github.com/i3/i3/issues/4220#issue-722082797 that need to be looked at before the release.

If any others are relevant that anyone knows of, please mention them.

**Comment by Airblader** [comment]
@stapelberg @orestisfl If there's going to be release within the next couple weeks as planned I think we should stop merging things other than (important) bugfixes until after the release.

**Comment by stapelberg** [comment]
Agreed. I wanted to do another pass of release prep this weekend, and probably do a release no later than the weekend after.

**Comment by stapelberg** [comment]
I decided that point “i3-msg and whitespace https://github.com/i3/i3/issues/4157 / https://github.com/i3/i3/pull/4237” is not easy enough to qualify for a last-minute fix before the 4.19 release after all.

I’ll focus on the meson points now.

**Comment by stapelberg** [comment]
4.19 now released!
