### ISSUE TITLE
enhancement: documentation: translations and versioned sections, move to markdown

### ISSUE THREAD

**Issue by stapelberg** [i3/i3#4327]
**Status:** https://github.com/i3/translation and https://github.com/stapelberg/i3/commits/markdown are where things stand. I’m not currently actively working on this.

---

I have been thinking about how to support community-contributed translations of i3 documentation. In particular, I see the following constraints:

* Translating a whole document can be a lot of work, so partial translations should be easily possible.
* Documents change, so translations must be marked as out of date, ideally on a per-section level.
* Additional tooling should be preferred over additional hosted services. While there are plenty of services for **string translation** within a program (e.g. weblate), I wasn’t able to find a service that would help with **document translation** anyway.

## Proposal

I propose we convert our current asciidoc documentation into markdown.

Using markdown will allow us to easily write tools that make translations easier to manage for our release/contribution workflow.

As a side benefit, over the last few years, markdown has strongly overtaken asciidoc in popularity, so contributors will have an easier time, too.

Once the documentation is in markdown, we will **annotate headings with the translation status**, for example:

```
### Mouse bindings {#_mouse_bindings introduced="4_16" translated="4_18"}

A mouse binding makes i3 execute a command upon pressing a specific mouse…
```

We then use a custom markdown renderer (built on the well-established [goldmark](https://pkg.go.dev/github.com/yuin/goldmark) package) which converts our custom attributes into the desired HTML output.

You can find an initial sketch of `tl8-render` in the https://github.com/i3/translation repository.

Other markdown tools will still be able to make sense of our documents, but translation status will only be rendered when using our tool of course.

For our tooling to work, **all** headings must have an id, and that id must be consistent across translations. For switching from asciidoc to markdown, we already must ensure that all headings have the same id as they had before, in order to not break any (external or internal) links.

Translations will live in the https://github.com/i3/i3.github.io website repository, because they are based on released documentation, not in-development documentation.

As a nice bonus, versioned documentation as discussed in issue #2563 will become trivial to implement with this approach.

### Example: starting a new translation

```
git cp _docs/userguide.markdown _docs/fr/userguide.markdown
tl8-new _docs/fr/userguide.markdown  # marks all sections as untranslated
```

### Example: new i3 release / out-of-date sections

When we do a new release, our release.sh automation would call `tl8-flag` like so:

```
tl8-flag _docs/userguide.markdown  # flags changed sections as out of date in _docs/*/userguide.markdown 
```

Here’s a mockup of how an out-of-date section would be rendered with `tl8-render`:

![section flagged out-of-date](https://user-images.githubusercontent.com/55506/105573225-46bb8180-5d5c-11eb-9390-60a877e682f2.jpg)

(Obviously default keybindings were not only introduced in i3 v4.16, but I wanted to illustrate versioned documentation as well.)

## TODO list

* [x] implement tooling and submit it into the i3 repository so that it is versioned/released with the rest of i3
* [x] find a markdown-to-HTML converter that Linux distribution packaging can use
  * there are many (python-markdown, pandoc, the original markdown, …), but distributions should most likely not rebuild the docs and just use the HTML versions from our release tarball. Even Debian doesn’t rebuild.
* [ ] convert our documentation to markdown
  * [ ] docs/debugging
  * [ ] docs/hacking-howto
  * [ ] docs/userguide.markdown
  * [ ] docs/ipc
  * [ ] docs/multi-monitor
  * [ ] docs/wsbar
  * [ ] docs/testsuite
  * [ ] docs/i3bar-protocol
  * [ ] docs/layout-saving
* [ ] update release.sh to deal with translations

**Comment by i3bot** [comment]
Please note that new features which require additional configuration will usually not be considered. We are happy with the feature set of i3 and want to focus in fixing bugs instead. We do accept feature requests, however, and will evaluate whether the added benefit (clearly) outweighs the complexity it adds to i3.

**Comment by Airblader** [comment]
This means that after a release we'd have to update all sections for all languages to mark them as up to date, right? Given that most sections typically don't change during a release I wonder if it wouldn't be better to not do that on section-level?

**Comment by stapelberg** [comment]
> we'd have to update all sections for all languages to mark them as up to date, right

The `tl8-flag` tool automatically marks sections as outdated in translations when they change in the original.

We want the section-level granularity so that most of the document stays up-to-date, and only sections that changed will be flagged (→ users will see more known-up-to-date documentation).

**Comment by Airblader** [comment]
I see, yeah, if the tool takes care of that, that's great. :-)

**Comment by thoughtsunificator** [comment]
I mean we're missing the whole point here, it's not to make things easier for people writing the documentation, it should be easier for everyone, readers included.

I think there should be multiple versions of the documentation:

- Editing (anything I don't think that matters)
- Raw (text as in those .txt files that seem to have disappeared) 
- Interop: Man page etc..
- Fast browsing (#4406)

Tagging should be as lightweight as possible and there should always be a raw, txt version of the documentation, I have honestly no idea why it is so hard to find any even outside i3. 

i3 could very well keep asciidoc assuming the toolchain stays light and do not try to take over the entire documentation with its weird syntax or whatever.

Final point is to seriously try to think about people reading the documentation instead of having that mindset where it's fine as long as the information is out there. 
The information should flow easily, that goes without saying that if the documentation is large enough there should be a ToC, it should be ordered and structured.

The most important part of the documentation is what led to i3 and yet it somehow managed not to be in it. There should be both theorical and technical knowledge, it goes without saying that starting with key bindings makes absolutely no sense.

A documentation for any writer and any reader. I don't think it's that hard.
